<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautic',
	'db_user' => 'root',
	'db_password' => 'root',
	'db_server_version' => '5.7.17-0ubuntu0.16.04.1',
	'mailer_from_name' => 'admin Admin',
	'mailer_from_email' => 'adminmail@mail.org.ua',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '81c3ce9a055b8b0a9433dab18ba8176595bc69d33de555a956959814eabe7d17',
	'site_url' => 'http://nautic.dev',
);
